# A clustered setup with federation
services:
  etcd-server:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd-server
    hostname: etcd-server
    ports:
      - "2379:2379"
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
    networks:
      event-notification:
        ipv4_address: 172.28.0.10
        aliases:
          - etcd-server

  cluster1:
    build:
      context: ../../../.
      dockerfile: Dockerfile.scratch
    container_name: cluster1
    hostname: cluster1.local
    environment:
      MINIO_ETCD_ENDPOINTS: http://etcd-server:2379
      MINIO_ETCD_COREDNS_PATH: /skydns
      MINIO_DOMAIN: local
      MINIO_PUBLIC_IPS: 172.28.0.11
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    command: ["server", "http://cluster1.local/data/disk{1...4}"]
    ports:
      - "11000:9000"
      - "11001:9001"
    networks:
      event-notification:
        ipv4_address: 172.28.0.11
        aliases:
          - cluster1.local

  cluster2:
    build:
      context: ../../../.
      dockerfile: Dockerfile.scratch
    container_name: cluster2
    hostname: cluster2.local
    environment:
      MINIO_ETCD_ENDPOINTS: http://etcd-server:2379
      MINIO_ETCD_COREDNS_PATH: /skydns
      MINIO_DOMAIN: local
      MINIO_PUBLIC_IPS: 172.28.0.12
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: ["server", "http://cluster2.local/data/disk{1...4}"]
    ports:
      - "12000:9000"
      - "12001:9001"
    networks:
      event-notification:
        ipv4_address: 172.28.0.12
        aliases:
          - cluster2.local

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      event-notification:
        ipv4_address: 172.28.0.13
        aliases:
          - mongo-server     

networks:
  event-notification:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
